name: Academy pipeline exercise

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3
      
      - name: Print name
        run: echo Hello, Aleksi Rendel!

      - name: Print node version
        run: npm --version
